# **Tratamiento de errores**

```py
try:
    a = 5
    b = '0'
    print(a / b)
except:
    print('Some error occurred.')

print("Out of try except blocks.")
```

```sh
Some error occurred.
Out of try except blocks.

Process finished with exit code 0
```
